# Generated by Django 3.2.3 on 2021-05-30 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Wa', 'Water'), ('Gr', 'Ground'), ('Fl', 'Flying')], default='Gr', max_length=2)),
                ('img', models.ImageField(blank=True, upload_to='AVIARY')),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Hu', 'Hunter'), ('He', 'Herbivores'), ('Om', 'Omnivores')], default='Om', max_length=2)),
                ('img', models.ImageField(blank=True, upload_to='ANIMALIA')),
                ('slug', models.SlugField(allow_unicode=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_app.aviary')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='ANIMAL')),
                ('slug', models.SlugField(allow_unicode=True)),
                ('AnimaliaType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_app.animalia')),
            ],
        ),
    ]
